/**
 * Solution by Luis Galotti
 * Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
  find the sum of the even-valued terms.
*/
 
#include <iostream>

using namespace std;
int nextFibon(int x = 1, int y = 1);

int nextFibon(int x, int y){
    return (x + y);
}
int main()
{
    
    int solution = 0;
    int number = 1;
    int previousNumber = 1;
    while (number < 4000000){
        if (number % 2 == 0) solution += number;
        int aux = number;
        number = nextFibon(number, previousNumber);
        previousNumber = aux;
    }
    
  printf("Solution =  %i", solution); 
   
   return 0;
}
